=== mstemen0010/anti-freeze/build/classes/com/wms/antifreeze/gui/resources/PolyImageMapXmlSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/PolyImageMapXmlSchema"
    xmlns:tns="http://xml.netbeans.org/schema/PolyImageMapXmlSchema"
    elementFormDefault="qualified" version="1.0" attributeFormDefault="qualified">
    <xsd:complexType name="PolyPoint">
        <xsd:sequence maxOccurs="1" minOccurs="1">
            <xsd:element name="xCoordinate" type="xsd:unsignedInt"></xsd:element>
            <xsd:element name="yCoordinate" type="xsd:unsignedInt"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="PolyMapArea">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="AreaName" type="xsd:string"/>
            <xsd:element name="AreaImage" type="xsd:string"/>
            <xsd:element name="Points" maxOccurs="unbounded" type="tns:PolyPoint"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="PolyMapGroup">
        <xsd:sequence maxOccurs="1">
            <xsd:element name="PolyMapGroupName" type="xsd:string"/>
            <xsd:element name="PolyMapGroupImage" type="xsd:string"/>
            <xsd:element name="PolyMapGroupArea" type="tns:PolyMapArea"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="PGroup">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="Member" type="tns:PolyMapGroup"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="Comment" type="xsd:string"/>
    <xsd:element name="PolyMapName" type="xsd:string"/>
    <xsd:element name="PolyMapGroups" type="tns:PolyMapGroup"></xsd:element>
    <xsd:element name="PolyMapBaseImage" type="xsd:string"/>
</xsd:schema>

=== mstemen0010/anti-freeze/build/classes/com/wms/antifreeze/gui/resources/PolyImageMapXmlSchema1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : PolyImageMapXmlSchema1.xml
    Created on : June 29, 2009, 5:07 PM
    Author     : mstemen
    Description:
        Purpose of the document follows.
-->

<ns0:PolyMapGroups  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/PolyImageMapXmlSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/PolyImageMapXmlSchema PolyImageMapXmlSchema.xsd'>
    <ns0:PolyMapGroupName></ns0:PolyMapGroupName>
    <ns0:PolyMapGroupImage></ns0:PolyMapGroupImage>
    <ns0:PolyMapGroupArea>
        <ns0:AreaName></ns0:AreaName>
        <ns0:AreaImage></ns0:AreaImage>
        <ns0:Points>
            <ns0:xCoordinate>113</ns0:xCoordinate>
            <ns0:yCoordinate>1</ns0:yCoordinate>
        </ns0:Points>
        <ns0:Points>
            <ns0:xCoordinate>123</ns0:xCoordinate>
            <ns0:yCoordinate>1</ns0:yCoordinate>
        </ns0:Points>
        <ns0:Points>
            <ns0:xCoordinate>84</ns0:xCoordinate>
            <ns0:yCoordinate>113</ns0:yCoordinate>
        </ns0:Points>
    </ns0:PolyMapGroupArea>

</ns0:PolyMapGroups>

=== mstemen0010/anti-freeze/src/com/wms/antifreeze/gui/resources/polymap/engine/EngineJobsPolyMap.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : EngineJobsPolyMap.xml
    Created on : June 27, 2009, 6:56 PM
    Author     : mstemen
    Description:
        Purpose of the document follows.
-->

<PolyMapGroups  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='http://xml.netbeans.org/schema/PolyImageMapXmlSchema'
   xsi:schemaLocation='http://xml.netbeans.org/schema/PolyImageMapXmlSchema file:/Users/mstemen/dev/java/projects/AntiFrieze/src/com/wms/antifrieze/gui/resources/PolyImageMapXmlSchema.xsd'>
    <PolyMapGroup>
        <ns1:PolyMapGroupName>EngineMap</ns1:PolyMapGroupName>
        <ns1:PolyMapGroupImage>engineBase.icon</ns1:PolyMapGroupImage>
        <ns1:PolyMapGroupArea>
            <ns1:AreaName>Transmission</ns1:AreaName>
            <ns1:AreaImage>engineTransmission.icon</ns1:AreaImage>
            <ns1:Points>
                <ns1:xCoordinate>113</ns1:xCoordinate>
                <ns1:yCoordinate>1</ns1:yCoordinate>
            </ns1:Points>
            <ns1:Points>
                <ns1:xCoordinate>123</ns1:xCoordinate>
                <ns1:yCoordinate>1</ns1:yCoordinate>
            </ns1:Points>
            <ns1:Points>
                <ns1:xCoordinate>84</ns1:xCoordinate>
                <ns1:yCoordinate>113</ns1:yCoordinate>
            </ns1:Points>
            <ns1:Points>
                <ns1:xCoordinate>149</ns1:xCoordinate>
                <ns1:yCoordinate>113</ns1:yCoordinate>
            </ns1:Points>

        </ns1:PolyMapGroupArea>
    </PolyMapGroup>

</PolyMapGroups>
